  At end of instruction 1
    ac    x   sp   pc   t1    q   t2   t3   t4   t5  mar  mdr   ir cvzn
     4 FFFF    0    6    1    6    0    0    4    0    1    4  A00 1110 
  At end of instruction 2
    ac    x   sp   pc   t1    q   t2   t3   t4   t5  mar  mdr   ir cvzn
     4 FFFF    0    7    1 FFFF    0    0    4    0    6   31   31 1111 
  At end of instruction 3
    ac    x   sp   pc   t1    q   t2   t3   t4   t5  mar  mdr   ir cvzn
     4 FFFF    0    8    1    8    0    0    4    0    7   28   28 0111 
  At end of instruction 4
    ac    x   sp   pc   t1    q   t2   t3   t4   t5  mar  mdr   ir cvzn
     4 FFFF    0    9    1    9    0    0    4    0    8   24   24 0011 
  At end of instruction 5
    ac    x   sp   pc   t1    q   t2   t3   t4   t5  mar  mdr   ir cvzn
     4 FFFF    0    A    1    1    0    0    4    0    9   22   22 0001 
  At end of instruction 6
    ac    x   sp   pc   t1    q   t2   t3   t4   t5  mar  mdr   ir cvzn
     4 FFFF    0    B    1    0    0    0    4    0    A   21   21 0000 
  At end of instruction 7
    ac    x   sp   pc   t1    q   t2   t3   t4   t5  mar  mdr   ir cvzn
     4 FFFF    0    C    1 FFFF    0    0    4    0    B   31   31 0001 
  At end of instruction 8
    ac    x   sp   pc   t1    q   t2   t3   t4   t5  mar  mdr   ir cvzn
     4 FFFF    0    D    1    0    0    0    4    0    C   32   32 0011 
  At end of instruction 9
    ac    x   sp   pc   t1    q   t2   t3   t4   t5  mar  mdr   ir cvzn
     4 FFFF    0    E    1    E    0    0    4    0    D   34   34 0111 
  At end of instruction 10
    ac    x   sp   pc   t1    q   t2   t3   t4   t5  mar  mdr   ir cvzn
     4 FFFF    0    F    1    F    0    0    4    0    E   38   38 1111 
